#!/usr/bin/env python3
"""
Strips auto-generated content from markdown files before commit.

Replaces content between AUTO-GENERATED markers with placeholder text
so that commits don't include regenerated output that changes frequently.
"""

import re
import sys
from pathlib import Path

# Patterns for both regular and full auto-generated sections
PATTERN = re.compile(
    r'(<!-- AUTO-GENERATED(?:-FULL)?:START -->)\n'
    r'```\n'
    r'.*?'
    r'```\n'
    r'(<!-- AUTO-GENERATED(?:-FULL)?:END -->)',
    re.DOTALL
)

PLACEHOLDER = '''```
...
```
'''


def strip_autogenerated(content: str) -> str:
    """Replace auto-generated sections with placeholder."""
    def replacer(match):
        start_marker = match.group(1)
        end_marker = match.group(2)
        return f'{start_marker}\n{PLACEHOLDER}{end_marker}'

    return PATTERN.sub(replacer, content)


def process_file(filepath: Path) -> bool:
    """Process a single file. Returns True if file was modified."""
    content = filepath.read_text()
    new_content = strip_autogenerated(content)

    if content != new_content:
        filepath.write_text(new_content)
        return True
    return False


def main():
    """Process all markdown files in src/ directory."""
    src_dir = Path(__file__).parent.parent / 'src'

    if not src_dir.exists():
        print(f"Error: src directory not found at {src_dir}", file=sys.stderr)
        sys.exit(1)

    print("Pre-commit hook: checking auto-generated content...")

    modified = []
    for md_file in src_dir.rglob('*.md'):
        if process_file(md_file):
            modified.append(md_file)

    if modified:
        print(f"Stripped auto-generated content from {len(modified)} file(s):")
        for f in modified:
            print(f"  - {f.relative_to(src_dir.parent)}")
        # Re-stage the modified files
        import subprocess
        for f in modified:
            subprocess.run(['git', 'add', str(f)], check=True)
    else:
        print("No auto-generated content to strip.")

    return 0


if __name__ == '__main__':
    sys.exit(main())
